# -*- coding: utf-8 -*-
"""Premier League Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_tVDRkNmicMnEU2871riFMZaKUQNOsAl
"""

import requests
url='https://www.skysports.com/premier-league-table/2019'
page=requests.get(url)

#print(page)

#print(page.text)

from bs4 import BeautifulSoup

soup = BeautifulSoup(page.text,'html.parser')

#print(soup.prettify)

#print(soup.find('a'))

#print(soup.find_all('a'))

league = soup.find('table',class_='standing-table__table')

#print(league)

league_table = soup.find_all('tbody')

#print(league_table)

for team in league_table:
  rows=team.find_all('tr')
  #print(row)
  for each in rows:
    num = each.find('td',class_='standing-table__cell').text.strip()
    team_names = each.find('td', class_='standing-table__cell standing-table__cell--name').text.strip()
    team_points = each.find_all('td', class_ = 'standing-table__cell')[9].text
    print("%s.  %s %s" %(num, team_names, team_points))

import pandas as pd

league_2019 = []
for team in league_table:
  rows=team.find_all('tr')
  for each in rows:
    team_names = each.find('td', class_='standing-table__cell standing-table__cell--name').text.strip()
    team_points = each.find_all('td', class_ = 'standing-table__cell')[9].text
    league_dict={'names':team_names,
                 'points':team_points}
    league_2019.append(league_dict)

df = pd.DataFrame(league_2019)

df.head()

df